{
  "Header": {
    "Original": "CVE-2020-8632 (In cloud-init through 19.4, rand_user_password in cloudinit/config/cc_ ...)",
    "Line": 191958,
    "ID": "CVE-2020-8632",
    "Description": "(In cloud-init through 19.4, rand_user_password in cloudinit/config/cc_ ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2113-1}",
      "Line": 191959,
      "Type": "xref",
      "Bugs": [
        "DLA-2113-1"
      ]
    },
    {
      "Original": "- cloud-init 19.4-2 (bug #951363)",
      "Line": 191960,
      "Type": "package",
      "Package": "cloud-init",
      "Kind": "fixed",
      "Version": "19.4-2",
      "BugNo": 951363
    },
    {
      "Original": "[buster] - cloud-init \u003cno-dsa\u003e (Minor issue)",
      "Line": 191961,
      "Type": "package",
      "Release": "buster",
      "Package": "cloud-init",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[stretch] - cloud-init \u003cno-dsa\u003e (Minor issue)",
      "Line": 191962,
      "Type": "package",
      "Release": "stretch",
      "Package": "cloud-init",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1860795",
      "Line": 191963,
      "Type": "NOTE",
      "Description": "https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1860795"
    },
    {
      "Original": "NOTE: https://github.com/canonical/cloud-init/pull/189",
      "Line": 191964,
      "Type": "NOTE",
      "Description": "https://github.com/canonical/cloud-init/pull/189"
    },
    {
      "Original": "NOTE: https://github.com/canonical/cloud-init/commit/42788bf24a1a0a5421a2d00a7f59b59e38ba1a14",
      "Line": 191965,
      "Type": "NOTE",
      "Description": "https://github.com/canonical/cloud-init/commit/42788bf24a1a0a5421a2d00a7f59b59e38ba1a14"
    }
  ]
}