{
  "Header": {
    "Original": "CVE-2022-2996 (A flaw was found in the python-scciclient when making an HTTPS connect ...)",
    "Line": 12099,
    "ID": "CVE-2022-2996",
    "Description": "(A flaw was found in the python-scciclient when making an HTTPS connect ...)"
  },
  "Annotations": [
    {
      "Original": "- python-scciclient \u003cunfixed\u003e (bug #1018213)",
      "Line": 12100,
      "Type": "package",
      "Package": "python-scciclient",
      "Kind": "unfixed",
      "BugNo": 1018213
    },
    {
      "Original": "[bullseye] - python-scciclient \u003cno-dsa\u003e (Minor issue)",
      "Line": 12101,
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-scciclient",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c (0.12)",
      "Line": 12102,
      "Type": "NOTE",
      "Description": "https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c (0.12)"
    }
  ]
}