{
  "Header": {
    "Original": "CVE-2018-10999 (An issue was discovered in Exiv2 0.26. The Exiv2::Internal::PngChunk:: ...)",
    "Line": 294966,
    "ID": "CVE-2018-10999",
    "Description": "(An issue was discovered in Exiv2 0.26. The Exiv2::Internal::PngChunk:: ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4238-1 DLA-1551-1 DLA-1402-1}",
      "Line": 294967,
      "Type": "xref",
      "Bugs": [
        "DSA-4238-1",
        "DLA-1551-1",
        "DLA-1402-1"
      ]
    },
    {
      "Original": "- exiv2 0.25-4",
      "Line": 294968,
      "Type": "package",
      "Package": "exiv2",
      "Kind": "fixed",
      "Version": "0.25-4"
    },
    {
      "Original": "NOTE: https://github.com/Exiv2/exiv2/issues/306",
      "Line": 294969,
      "Type": "NOTE",
      "Description": "https://github.com/Exiv2/exiv2/issues/306"
    },
    {
      "Original": "NOTE: https://github.com/Exiv2/exiv2/commit/2fb00c8a16ce93756cddd70536e361a49369ba88",
      "Line": 294970,
      "Type": "NOTE",
      "Description": "https://github.com/Exiv2/exiv2/commit/2fb00c8a16ce93756cddd70536e361a49369ba88"
    },
    {
      "Original": "NOTE: https://github.com/Exiv2/exiv2/commit/3ad0050469e6ea63b4081f2a88c264ce8ab55c51",
      "Line": 294971,
      "Type": "NOTE",
      "Description": "https://github.com/Exiv2/exiv2/commit/3ad0050469e6ea63b4081f2a88c264ce8ab55c51"
    }
  ]
}