{
  "Header": {
    "Original": "CVE-2021-3429",
    "Line": 112371,
    "ID": "CVE-2021-3429"
  },
  "Annotations": [
    {
      "Original": "RESERVED",
      "Line": 112372,
      "Type": "RESERVED"
    },
    {
      "Original": "{DLA-2601-1}",
      "Line": 112373,
      "Type": "xref",
      "Bugs": [
        "DLA-2601-1"
      ]
    },
    {
      "Original": "- cloud-init 20.4.1-2 (bug #985540)",
      "Line": 112374,
      "Type": "package",
      "Package": "cloud-init",
      "Kind": "fixed",
      "Version": "20.4.1-2",
      "BugNo": 985540
    },
    {
      "Original": "[buster] - cloud-init 20.2-2~deb10u2",
      "Line": 112375,
      "Type": "package",
      "Release": "buster",
      "Package": "cloud-init",
      "Kind": "fixed",
      "Version": "20.2-2~deb10u2"
    },
    {
      "Original": "NOTE: https://github.com/canonical/cloud-init/commit/b794d426b9ab43ea9d6371477466070d86e10668",
      "Line": 112376,
      "Type": "NOTE",
      "Description": "https://github.com/canonical/cloud-init/commit/b794d426b9ab43ea9d6371477466070d86e10668"
    }
  ]
}