{
  "Header": {
    "Original": "CVE-2019-15939 (An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero err ...)",
    "Line": 224482,
    "ID": "CVE-2019-15939",
    "Description": "(An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero err ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2799-1}",
      "Line": 224483,
      "Type": "xref",
      "Bugs": [
        "DLA-2799-1"
      ]
    },
    {
      "Original": "- opencv 4.1.2+dfsg-3",
      "Line": 224484,
      "Type": "package",
      "Package": "opencv",
      "Kind": "fixed",
      "Version": "4.1.2+dfsg-3"
    },
    {
      "Original": "[buster] - opencv \u003cno-dsa\u003e (Minor issue)",
      "Line": 224485,
      "Type": "package",
      "Release": "buster",
      "Package": "opencv",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - opencv \u003cno-dsa\u003e (Minor issue)",
      "Line": 224486,
      "Type": "package",
      "Release": "jessie",
      "Package": "opencv",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/OpenCV/opencv/issues/15287",
      "Line": 224487,
      "Type": "NOTE",
      "Description": "https://github.com/OpenCV/opencv/issues/15287"
    },
    {
      "Original": "NOTE: https://github.com/opencv/opencv/pull/15382",
      "Line": 224488,
      "Type": "NOTE",
      "Description": "https://github.com/opencv/opencv/pull/15382"
    }
  ]
}